### ISSUE TITLE
`--app` argument needed for modern(?) chromium versions

### ISSUE THREAD

**Issue by hairmare** [xtrinch/ansible-role-kiosk#3]
I needed to call the role with the following var for the session crash bubble not to show up (I'm on Rasbian Stretch btw.).
 
```yaml
website_url: "--app=http://www.google.com"
```
This was basically the first solution that worked from this SO post: https://raspberrypi.stackexchange.com/a/85827

I was also considering adding the `--app=` part in the service template itself on the following line.

https://github.com/xtrinch/ansible-role-kiosk/blob/fc252390e39b9051fcfd26b5e3ef1851eb139d50/templates/kiosk.service.j2#L7

I'm not really sure when the `--app` arg became the way to get rid of the bubble but --disable-session-crashed-bubble alone doesn't seem to do the job anymore.

I would have created a PR with the change but wanted to get your input since you might know if this has any implications for older supported operating systems.

**Comment by xtrinch** [comment]
Well I've been looking for a way to solve this, and this should be an alright solution for most cases, so I'll gladly accept a pull request.
